
development:
  adapter: postgresql
  encoding: unicode
  database: knkf_development
  pool: 5

test:
  adapter: postgresql
  encoding: UTF8
  database: knkf_development_test
  pool: 5

production:
  adapter: postgresql
  encoding: UTF8
  database: knkf_development_production
  pool: 5
  username: vagrant